## Linear Regression with direct gradient descent

In [3]:
import tensorflow as tf

W=tf.Variable(tf.random_uniform([1], -100, 100))
X=tf.placeholder(tf.float32)
Y=tf.placeholder(tf.float32)

model = W * X

# L2 cost function 
cost = tf.reduce_mean (tf.square(model - Y))

#
gd = W - tf.multiply(0.1,
                    tf.reduce_mean(
                        tf.multiply(model-Y, X)))
update = W.assign (gd)

# initialize 
ss = tf.Session()
ss.run (tf.global_variables_initializer())

# fit to data
xin = [1, 2, 3]
yin = [1., 2, 3]
feed_dict={X: xin, Y:yin}
for i in range(20):
    ss.run (update, feed_dict=feed_dict)
    print (i, ss.run(cost, feed_dict=feed_dict), ss.run(W))

0 46.8535 [-2.16860342]
1 13.3272 [-0.68992186]
2 3.79086 [ 0.09870839]
3 1.07829 [ 0.51931119]
4 0.306713 [ 0.74363267]
5 0.0872428 [ 0.86327076]
6 0.0248157 [ 0.92707777]
7 0.00705869 [ 0.96110815]
8 0.0020078 [ 0.9792577]
9 0.000571107 [ 0.98893744]
10 0.000162449 [ 0.99409997]
11 4.62065e-05 [ 0.99685335]
12 1.31434e-05 [ 0.99832177]
13 3.73892e-06 [ 0.99910492]
14 1.06352e-06 [ 0.99952263]
15 3.02401e-07 [ 0.99974543]
16 8.60025e-08 [ 0.99986422]
17 2.44662e-08 [ 0.99992758]
18 6.96173e-09 [ 0.99996138]
19 1.98973e-09 [ 0.99997938]


## Multi-variable linear regression
$y = w_1 x_1 + w_2 x_2 + b = [b, w_1, w_2 ] [1; x_1; x_2] $

In [22]:
x_in = [[1,1,1,1,1],
        [0, 2, 0, 4, 0],
        [1.,0,3,0,5] ]
y_in = [[1, 2, 3, 4, 5]]

W = tf.Variable(tf.random_uniform([1,3], -1.,1.))

model = tf.matmul (W, x_in)
cost = tf.reduce_mean (tf.square(model - y_in))


a=tf.Variable(0.1)
opt = tf.train.GradientDescentOptimizer(learning_rate=a)
train = opt.minimize(cost)

# initialize 
ss = tf.Session()
ss.run (tf.global_variables_initializer())

# fit to data
for i in range(1001):
    ss.run (train)
    if i%200 == 0:
        print (i, ss.run(cost), ss.run(W))

print ('done.')

0 0.259726 [[ 0.96568108  0.56886142  0.79722333]]
200 7.20708e-07 [[ 0.00201244  0.99937236  0.99947101]]
400 3.16049e-12 [[  4.04360117e-06   9.99998689e-01   9.99998868e-01]]
600 4.83169e-14 [[  1.62147217e-07   9.99999940e-01   9.99999940e-01]]
800 4.83169e-14 [[  1.62147217e-07   9.99999940e-01   9.99999940e-01]]
1000 4.83169e-14 [[  1.62147217e-07   9.99999940e-01   9.99999940e-01]]
done.


*Input data can be fed at learning time using the option ``Session.run()`` ``feed_dict``

In [24]:
x_in = [[1.,1,1,1,1],
        [1,0,3,0,5],
        [0, 2, 0, 4, 0]
       ]
y_in = [[1., 2, 3, 4, 5]]

W = tf.Variable(tf.random_uniform([1,3], -1.,1))
X = tf.placeholder(tf.float32, shape=(3,5))
Y = tf.placeholder(tf.float32, shape=(1,5))

model = tf.matmul (W,X)
cost = tf.reduce_mean (tf.square(model - Y))

a=tf.Variable(0.1)
opt = tf.train.GradientDescentOptimizer(learning_rate=a)
train = opt.minimize(cost)

# initialize 
ss = tf.Session()
ss.run (tf.global_variables_initializer())

# fit to data
feed_dict={X: x_in, Y:y_in}
for i in range(1001):
    ss.run (train, feed_dict=feed_dict)
    if i%200 == 0:
        print (i, ss.run(cost, feed_dict=feed_dict), ss.run(W))
print ('done.')

0 0.788047 [[ 0.12009734  1.26336324  0.75217521]]
200 8.8931e-09 [[  2.23626019e-04   9.99941230e-01   9.99930263e-01]]
400 6.82121e-14 [[  5.56843872e-07   9.99999881e-01   9.99999821e-01]]
600 1.42109e-14 [[  1.75374353e-07   1.00000000e+00   9.99999940e-01]]
800 1.42109e-14 [[  1.75374353e-07   1.00000000e+00   9.99999940e-01]]
1000 1.42109e-14 [[  1.75374353e-07   1.00000000e+00   9.99999940e-01]]
1200 1.42109e-14 [[  1.75374353e-07   1.00000000e+00   9.99999940e-01]]
1400 1.42109e-14 [[  1.75374353e-07   1.00000000e+00   9.99999940e-01]]
1600 1.42109e-14 [[  1.75374353e-07   1.00000000e+00   9.99999940e-01]]
1800 1.42109e-14 [[  1.75374353e-07   1.00000000e+00   9.99999940e-01]]
2000 1.42109e-14 [[  1.75374353e-07   1.00000000e+00   9.99999940e-01]]
done.


## data loading from file
- ``np.loadtxt()`` reads the txt datafile and do transposition!

- tf.placeholder() may use ``shape=data.shape``

In [32]:
import numpy as np
xy = np.loadtxt ('train.txt', unpack=True, dtype='float32')
xdata = xy[0:-1]
ydata = xy[-1]
print ('xy=', xy)
print ('xdata=', xdata, ' shape=', xdata.shape)
print('ydata=', ydata, ' shape=', ydata.shape)

W = tf.Variable(tf.random_uniform([1,len(xdata)], -1.,1))
X = tf.placeholder(tf.float32, shape=xdata.shape)
Y = tf.placeholder(tf.float32, shape=ydata.shape)

model = tf.matmul (W,X)
cost = tf.reduce_mean (tf.square(model - Y))

a=tf.Variable(0.1)
opt = tf.train.GradientDescentOptimizer(learning_rate=a)
train = opt.minimize(cost)

# initialize 
ss = tf.Session()
ss.run (tf.global_variables_initializer())

# fit to data
print ('## data fitting')
feed_dict={X: xdata, Y:ydata}
for i in range(1001):
    ss.run (train, feed_dict=feed_dict)
    if i%200 == 0:
        print (i, ss.run(cost, feed_dict=feed_dict), ss.run(W))
print ('done.')

xy= [[ 1.  1.  1.  1.  1.]
 [ 1.  0.  3.  0.  5.]
 [ 0.  2.  0.  4.  0.]
 [ 1.  2.  3.  4.  5.]]
xdata= [[ 1.  1.  1.  1.  1.]
 [ 1.  0.  3.  0.  5.]
 [ 0.  2.  0.  4.  0.]]  shape= (3, 5)
ydata= [ 1.  2.  3.  4.  5.]  shape= (5,)
## data fitting
0 7.04798 [[ 1.06557155  1.7138257   0.74394292]]
200 4.96941e-07 [[ 0.001671    0.99956065  0.99947882]]
400 2.00373e-12 [[  3.38706627e-06   9.99999106e-01   9.99998927e-01]]
600 1.42109e-14 [[  1.77952884e-07   1.00000000e+00   9.99999940e-01]]
800 1.42109e-14 [[  1.77952884e-07   1.00000000e+00   9.99999940e-01]]
1000 1.42109e-14 [[  1.77952884e-07   1.00000000e+00   9.99999940e-01]]
done.
